spring.application.name=to-do-back-end

spring.datasource.url=jdbc:postgresql://localhost:5432/to_do
spring.datasource.username=to_do_user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
